### ISSUE TITLE
Project constraints

### ISSUE THREAD

**Issue by KrystynaMil** [final-project-org/fp-11-12-1#4]

**Comment by businan** [comment]
7. Project Constraints                                         
-Will serve individuals over the age of 50    
-Will be limited to shopping assistance at the beginning of the project
-But the infrastructure will be set up to be open to additions
-This is non-profit application
-Will be a team of volunteer individuals who want to serve

**Comment by businan** [comment]
If another constraint comes to mind from my colleges, feel free to add 🙏
