### ISSUE TITLE
User interviews

### ISSUE THREAD

**Issue by KrystynaMil** [final-project-org/fp-11-12-1#5]
- [x] as a user, colleagues especially @Houcinos will be interviewed to collect the information.
- [x] this interview can happen during our daily meeting `17:30 28/04/2021` or we can decide another time in the meeting.
- [x] the [interview](https://github.com/final-project-org/fp-11-12-1/wiki/User-Interview) will be written in a [wiki](https://github.com/final-project-org/fp-11-12-1/wiki/User-Interview)  file then we can construct user stories from it. 
- [x] any suggestion or objection are most welcom. write your comments or tel in the meeting. :smiley:

**Comment by jraoul2002** [comment]
some questions in the interview are they relevant for our project ? @KrystynaMil

**Comment by tahminarasoli** [comment]
> 
> 
> some questions in the interview are they relevant for our project ? @KrystynaMil

@jraoul2002 you can write your own questions as well as you can answer existing ones.

**Comment by jraoul2002** [comment]
@tahminarasoli the idea is not to come out with 1000 questions but to agree on what we can ask. and that will be relevant for the project

**Comment by tahminarasoli** [comment]
> 
> 
> @tahminarasoli the idea is not to come out with 1000 questions but to agree on what we can ask. and that will be relevant for the project

@jraoul2002 the file that I created is just a start point you can do anything with it. you can propose yours, I and other colleagues will answer. for real projects, it's kind of standard to ask these questions but as I have mentioned it is not necessary to answer all of them.

**Comment by jraoul2002** [comment]
@KrystynaMil so if i understood well it is like a simulation to a real life project. @tahminarasoli  u should have explained like that not saying i should ask my own questions since i can answer all the suggested questions. 😄

**Comment by KrystynaMil** [comment]
@jraoul2002  That what our coaches asked as to do :)
